apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: aws-loadbalancing-crds
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: eks-git-charts
  path: ./stable/aws-load-balancer-controller/crds
  prune: true
  timeout: 5m0s
